before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }}"
    goos:
      - "darwin"
      - "freebsd"
      - "linux"
      - "windows"
    goarch:
      - "amd64"
      - "386"
      - "arm"
      - "arm64"
    goarm:
      - "6"
      - "7"

universal_binaries:
  - replace: false

archives:
  - format: tar.gz
    name_template: |-
      {{ .ProjectName }}-{{ .Version }}_{{ .Os }}_{{ if eq .Arch "all" }}universal{{ else }}{{ .Arch }}{{ end }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: macos

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  skip: true

dockers:
  - image_templates:
      - "ghcr.io/jimeh/casecmp:{{ .Version }}-amd64"
      - "ghcr.io/jimeh/casecmp:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/jimeh/casecmp:{{ .Version }}-386"
      - "ghcr.io/jimeh/casecmp:latest-386"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: "386"
    build_flag_templates:
      - "--platform=linux/386"
  - image_templates:
      - "ghcr.io/jimeh/casecmp:{{ .Version }}-arm64"
      - "ghcr.io/jimeh/casecmp:latest-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
  - image_templates:
      - "ghcr.io/jimeh/casecmp:{{ .Version }}-armv6"
      - "ghcr.io/jimeh/casecmp:latest-armv6"
    use: buildx
    goos: linux
    goarch: arm
    goarm: "6"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v6"
  - image_templates:
      - "ghcr.io/jimeh/casecmp:{{ .Version }}-armv7"
      - "ghcr.io/jimeh/casecmp:latest-armv7"
    use: buildx
    goos: linux
    goarch: arm
    goarm: "7"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v7"

docker_manifests:
  - name_template: ghcr.io/jimeh/casecmp:{{ .Version }}
    image_templates:
      - ghcr.io/jimeh/casecmp:{{ .Version }}-amd64
      - ghcr.io/jimeh/casecmp:{{ .Version }}-386
      - ghcr.io/jimeh/casecmp:{{ .Version }}-arm64
      - ghcr.io/jimeh/casecmp:{{ .Version }}-armv6
      - ghcr.io/jimeh/casecmp:{{ .Version }}-armv7
  - name_template: ghcr.io/jimeh/casecmp:latest
    image_templates:
      - ghcr.io/jimeh/casecmp:latest-amd64
      - ghcr.io/jimeh/casecmp:latest-386
      - ghcr.io/jimeh/casecmp:latest-arm64
      - ghcr.io/jimeh/casecmp:latest-armv6
      - ghcr.io/jimeh/casecmp:latest-armv7
